dataset:
  dataset_size: 200000
  max_text_length: 64
  fonts_dir: fonts
  images_dir: dataset_entrenamiento/dataset
  labels_path: dataset_entrenamiento/dataset/labels.txt
model:
  channels: 1
  include_blank: true
  input_height: 32
  input_width: 512
  vocab_chars: ' !%(),-./:;?@ABCDEFGHIJKLMN\ÑOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz[]¡¿ÁÉÍÑÓÚáéíñóú\0123456789+-./\\'
training:
  batch_size: 96
  checkpoint_dir: dataset_entrenamiento/checkpoints
  epochs: 100
  gradient_clip_norm: 1.0
  learning_rate: 0.001
  logs_dir: dataset_entrenamiento/logs
  warmup_epochs: 3
  scheduler:
    enable: true
    monitor: val_loss
    factor: 0.5      # Reducir LR a la mitad
    patience: 2      # Esperar 2 validaciones sin mejora (10 épocas)
    min_lr: 0.00001  # Límite inferior
    verbose: true
